/**
 * Author: Joe Morales (CSA)
 * Swagger REST Server
 */

var express = require("express"),
    os = require('os');

/**
 * Create Node Express REST Server
 */
function create(expressServer, options){

    var hostname = options.hostname || 'localhost';
    var port = options.port === undefined ? 8888 : options.port;
    var description = options.description === undefined ? "CSA REST" : options.description;
    var title = options.title === undefined ? "CSA REST" : options.title;

    /**
     * Create Swagger Server
     */
    var swg = require("swagger-node-express").createNew(expressServer);

    /**
     * API Configuration
     */
    swg.configureDeclaration("model", {
        description : options.description,
        authorizations : ["oauth2"],
        produces: ["application/json"]
    });

    swg.setApiInfo({
        title: options.title,
        description: "Generated by <a href=\"http://swagger.wordnik.com\">Swagger</a>."
    });

    /**
     * Set URL path where API docs will reside
     */
    swg.configureSwaggerPaths("", "api-docs", "")
    swg.configure("http://"+hostname+":" + port, "1.0.0");

    /**
     * Path to swagger auto-generated API UI
     */
    var docUiPath = __dirname + '/swagger-ui/dist';
    var docs_handler = express.static(docUiPath);

    /**
     * Set ExpressJS Route for API docs
     */
    expressServer.get(/^\/docs(\/.*)?$/, function(req, res, next) {

        if (req.url === '/docs') {
            res.writeHead(302, { 'Location' : req.url + '/' });
            res.end();
            return;
        }
        // Remove leading /docs so that connect locates file correctly
        req.url = req.url.substr('/docs'.length);

        return docs_handler(req, res, next);
    });


    // Expose method to add API endpoints
    swg.post = function(apiEndpoint){
        swg.addPost(apiEndpoint);
        swg.configure("https://"+hostname+":" + options.port, "1.0.0");
    }

    // Expose method to add API endpoints
    swg.patch = function(apiEndpoint){
        swg.addPatch(apiEndpoint);
        swg.configure("https://"+hostname+":" + options.port, "1.0.0");
    }

    // Expose method to add API endpoints
    swg.put = function(apiEndpoint){
        swg.addPut(apiEndpoint);
        swg.configure("https://"+hostname+":" + options.port, "1.0.0");
    }

    // Expose method to add API endpoints
    swg.get = function(apiEndpoint){
        swg.addGet(apiEndpoint);
        swg.configure("https://"+hostname+":" + options.port, "1.0.0");
    }

    // Expose method to add API endpoints
    swg.delete = function(apiEndpoint){
        swg.addDelete(apiEndpoint);
        swg.configure("https://"+hostname+":" + options.port, "1.0.0");
    }

    return swg;
}
exports.create=create;
